# playbook.yaml
---
- name: Install and Start Apache
  hosts: all
  become: true  # Run tasks with elevated privileges (sudo)

  tasks:
    - name: Install Apache
      apt:
        name: apache2
        state: present

    - name: Start Apache service
      systemd:
        name: apache2
        state: started

- name: Copy index.html to web servers
  hosts: all
  become: true  # Run tasks with elevated privileges (sudo)

  tasks:
    - name: Copy index.html
      copy:
        src: /home/ubuntu/index.html
        dest: /var/www/html/index.html

